import type { ProtocolDraft } from "@repo/ai/schemas";
import {
  DatabaseReader,
  DatabaseWriter,
} from "@repo/backend/confect/_generated/services";
import type { GenericId } from "convex/values";
import { Effect } from "effect";

import {
  currentProtocolInputs,
  maxProtocolItems,
  maxProtocolSections,
  maxProtocolSources,
} from "./helpers";

type ProtocolId = GenericId<"protocols">;

/** Returns all saved notes and transcripts for a protocol as one prompt string. */
export const getProtocolInputText = Effect.fn("protocols.getProtocolInputText")(
  function* (protocolId: ProtocolId) {
    const reader = yield* DatabaseReader;
    const inputs = yield* reader
      .table("protocolSources")
      .index("by_protocolId", (q) => q.eq("protocolId", protocolId))
      .take(maxProtocolSources);

    return currentProtocolInputs(inputs)
      .map((input) => input.text ?? "")
      .join("\n\n")
      .trim();
  }
);

/** Persists a generated protocol draft into reviewable sections and items. */
export const insertProtocolDraft = Effect.fn("protocols.insertProtocolDraft")(
  function* (input: {
    readonly protocolId: ProtocolId;
    readonly draft: ProtocolDraft;
  }) {
    const writer = yield* DatabaseWriter;
    const sectionIds = yield* Effect.all(
      input.draft.sections.map((section, index) =>
        writer.table("protocolSections").insert({
          protocolId: input.protocolId,
          title: section.title,
          body: section.body,
          order: index,
          createdAt: Date.now(),
        })
      )
    );

    yield* Effect.all(
      input.draft.sections.flatMap((section, sectionIndex) => {
        const sectionId = sectionIds[sectionIndex];

        if (!sectionId) {
          return [];
        }

        return section.items.map((item) =>
          writer.table("protocolItems").insert({
            protocolId: input.protocolId,
            sectionId,
            kind: item.kind,
            title: item.title,
            body: item.body,
            bauteil: item.bauteil,
            objectName: item.objectName,
            trade: item.trade,
            responsibleParty: item.responsibleParty,
            dueDate: item.dueDate,
            severity: item.severity,
            status: item.status ?? defaultRecordStatus(item.kind),
            citationsJson: JSON.stringify(item.citations),
            createdAt: Date.now(),
            updatedAt: Date.now(),
          })
        );
      })
    );
  }
);

/** Removes stale generated review rows before a fresh generation result is stored. */
export const clearProtocolDraft = Effect.fn("protocols.clearProtocolDraft")(
  function* (protocolId: ProtocolId) {
    const reader = yield* DatabaseReader;
    const writer = yield* DatabaseWriter;
    const sections = yield* reader
      .table("protocolSections")
      .index("by_protocolId", (q) => q.eq("protocolId", protocolId))
      .take(maxProtocolSections);
    const items = yield* reader
      .table("protocolItems")
      .index("by_protocolId", (q) => q.eq("protocolId", protocolId))
      .take(maxProtocolItems);

    yield* Effect.all(
      items.map((item) => writer.table("protocolItems").delete(item._id))
    );
    yield* Effect.all(
      sections.map((section) =>
        writer.table("protocolSections").delete(section._id)
      )
    );
  }
);

/** Provides status defaults for protocol records generated by the AI provider. */
function defaultRecordStatus(
  kind: ProtocolDraft["sections"][number]["items"][number]["kind"]
) {
  if (kind === "task" || kind === "risk" || kind === "concern") {
    return "open";
  }

  if (kind === "obstruction") {
    return "blocked";
  }

  return "recorded";
}
